[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[hints.enabled]]
binding = { key = "u", mods = "Control|Shift" } # "U" conflicts with fcitx
command = "open"
hyperlinks = true
post_processing = true
mouse.enabled = true
regex = """
(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|
git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
decorations = "buttonless"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[cursor]
vi_mode_style = "Block"

[colors]
cursor = { text = "#111111", cursor = "#f9fff9"}
